# This is the default config for Jekyll
# This is used for your local environment

# Site settings
title: Cloudscaling
footertitle: Cloudscaling Blog

email: randy.bias@emc.com
description: > # this means to ignore newlines until "baseurl:"
  Cloudscaling is the leading provider of on-premise elastic cloud infrastructure solutions to support dynamic applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cloudscaling.com" # the base hostname & protocol for your site

timezone:       America/Los_Angeles
locale:         en_us

twitter_username: randybias
github_username:  randybias
googleplus_username: 108444194906673112871
rss_url: feed.xml
linkedin_url: http://www.linkedin.com/in/randybias
# Build settings
markdown: kramdown
# configure kramdown
kramdown:
  parse_block_html: false

encoding: utf-8

# Blog Permalink
permalink:     '/:categories/:title/'

paginate: 10
paginate_path: "/blog/page/:num/"

author_dir: author

exclude:
    - node_modules
    - sass-cache
    - vendor
